name: Release
on: workflow_dispatch

jobs:
  run_mrpack_distributor:
    runs-on: ubuntu-latest
    name: Release on Modrinth & GitHub Releases
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - name: Download Peony from GH Releases
        run: wget "https://github.com/LilydevMC/Peony/releases/download/0.2.0-223e662/peony_Linux-x86_64.tar.gz"
      - name: Unzip Peony
        run: tar xvf peony_Linux-x86_64.tar.gz
      - run: chmod +x ./peony
      - name: Checkout Repository Files
        uses: actions/checkout@v4
      - name: Run release
        run: ./peony mod -d