name: Release
on: workflow_dispatch

jobs:
  run_mrpack_distributor:
    runs-on: ubuntu-latest
    name: Release on Modrinth & GitHub Releases
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - name: Install Peony from git repository
        uses: baptiste0928/cargo-install@v2
        with:
          crate: peony
          git: https://github.com/LilydevMC/Peony
          tag: 0.2.0-223e662
      - name: Checkout Repository Files
        uses: actions/checkout@v4
      - name: Run release
        run: peony mod -d